global using Bundle = AsmResolver.DotNet.Bundles.BundleManifest;
global using Assembly = AsmResolver.DotNet.AssemblyDefinition;
global using Module = AsmResolver.DotNet.ModuleDefinition;
global using Type = AsmResolver.DotNet.TypeDefinition;
global using Method = AsmResolver.DotNet.MethodDefinition;
global using Parameter = AsmResolver.DotNet.ParameterDefinition;
global using Property = AsmResolver.DotNet.PropertyDefinition;
global using Field = AsmResolver.DotNet.FieldDefinition;
global using Event = AsmResolver.DotNet.EventDefinition;
global using AsmResolver.DotNet.Bundles;
global using minifuscator.Utils;
global using minifuscator.Models;
global using minifuscator.Models.Settings;
global using minifuscator.Modules;